<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.gravijet.tabcompleter</groupId>
        <artifactId>TabCompleter-parent</artifactId>
        <version>2.0</version>
    </parent>

    <artifactId>tabcompleter-spigot</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>net.gravijet.tabcompleter</groupId>
            <artifactId>tabcompleter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- SnakeYAML is provided by Spigot at runtime -->
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.retrooper</groupId>
            <artifactId>packetevents-spigot</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>shade</goal></goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>com.github.retrooper.packetevents</pattern>
                                    <shadedPattern>net.gravijet.tabcompleter.libs.packetevents</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.github.retrooper.packetevents</pattern>
                                    <shadedPattern>net.gravijet.tabcompleter.libs.ipacketevents</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
